# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InvitationredirecturlCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, url: str=None, description: str=None):  # noqa: E501
        """InvitationredirecturlCreate - a model defined in Swagger

        :param url: The url of this InvitationredirecturlCreate.  # noqa: E501
        :type url: str
        :param description: The description of this InvitationredirecturlCreate.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'url': str,
            'description': str
        }

        self.attribute_map = {
            'url': 'url',
            'description': 'description'
        }

        self._url = url
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'InvitationredirecturlCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The invitationredirecturl_create of this InvitationredirecturlCreate.  # noqa: E501
        :rtype: InvitationredirecturlCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this InvitationredirecturlCreate.


        :return: The url of this InvitationredirecturlCreate.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this InvitationredirecturlCreate.


        :param url: The url of this InvitationredirecturlCreate.
        :type url: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def description(self) -> str:
        """Gets the description of this InvitationredirecturlCreate.


        :return: The description of this InvitationredirecturlCreate.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this InvitationredirecturlCreate.


        :param description: The description of this InvitationredirecturlCreate.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description
