# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserAndRoles(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_id: str=None, roles: List[str]=None):  # noqa: E501
        """UserAndRoles - a model defined in Swagger

        :param user_id: The user_id of this UserAndRoles.  # noqa: E501
        :type user_id: str
        :param roles: The roles of this UserAndRoles.  # noqa: E501
        :type roles: List[str]
        """
        self.swagger_types = {
            'user_id': str,
            'roles': List[str]
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'roles': 'roles'
        }

        self._user_id = user_id
        self._roles = roles

    @classmethod
    def from_dict(cls, dikt) -> 'UserAndRoles':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The user_and_roles of this UserAndRoles.  # noqa: E501
        :rtype: UserAndRoles
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this UserAndRoles.


        :return: The user_id of this UserAndRoles.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this UserAndRoles.


        :param user_id: The user_id of this UserAndRoles.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def roles(self) -> List[str]:
        """Gets the roles of this UserAndRoles.


        :return: The roles of this UserAndRoles.
        :rtype: List[str]
        """
        return self._roles

    @roles.setter
    def roles(self, roles: List[str]):
        """Sets the roles of this UserAndRoles.


        :param roles: The roles of this UserAndRoles.
        :type roles: List[str]
        """

        self._roles = roles
