"""empty message

Revision ID: 1c24f1c1e551
Revises: 08dce55f9b1f
Create Date: 2018-09-18 12:44:00.749796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c24f1c1e551'
down_revision = '08dce55f9b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_redirect_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invitation', sa.Column('invitation_redirect_url_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invitation', 'invitation_redirect_url', ['invitation_redirect_url_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitation', type_='foreignkey')
    op.drop_column('invitation', 'invitation_redirect_url_id')
    op.drop_table('invitation_redirect_url')
    # ### end Alembic commands ###
