"""empty message

Revision ID: 5b43a456e399
Revises: bf47ce5e7e69
Create Date: 2018-11-22 13:56:58.684846

"""
import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b43a456e399'
down_revision = 'bf47ce5e7e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'deletion_method_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'deletion_method_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
