"""empty message

Revision ID: bf7a651cb809
Revises: 1c24f1c1e551
Create Date: 2018-11-19 07:23:52.108302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7a651cb809'
down_revision = '1c24f1c1e551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('account_secret', sa.VARCHAR(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('account_secret')
    )
    op.create_index(op.f('ix_credentials_site_id'), 'credentials', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credentials_site_id'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
