"""empty message

Revision ID: c4095b0a2f3a
Revises: e8d15433bc60
Create Date: 2018-04-12 10:32:28.071538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4095b0a2f3a'
down_revision = 'e8d15433bc60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_site_client_id', table_name='site')
    op.drop_column('site', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_site_client_id', 'site', ['client_id'], unique=True)
    # ### end Alembic commands ###
