"""empty message

Revision ID: ca80be53b61f
Revises: d04c151b0355
Create Date: 2018-07-03 12:44:28.285098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca80be53b61f'
down_revision = 'd04c151b0355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.drop_column('invitation', 'is_system_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('is_system_user', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('invitation', 'organisation_id')
    # ### end Alembic commands ###
