"""empty message

Revision ID: d04c151b0355
Revises: c4095b0a2f3a
Create Date: 2018-04-12 10:32:54.710027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04c151b0355'
down_revision = 'c4095b0a2f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_site_client_id'), 'site', ['client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_client_id'), table_name='site')
    op.drop_column('site', 'client_id')
    # ### end Alembic commands ###
